import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { AuthProvider } from "../contexts/AuthContext";
import AuthModal from "./components/AuthModal";
import "./globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} font-sans min-h-full flex flex-col antialiased`}>
        <AuthProvider>
          <AuthModal />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
